export const actionTypes = {
    SET_RECIPES: "SET_RECIPES",
    SET_SEARCHED_RECIPE: "SET_SEARCHED_RECIPE",
    REMOVE_SEARCHED_RECIPE: "REMOVE_SEARCHED_RECIPE",
    SELECTED_RECIPE: "SELECTED_RECIPE",
    REMOVE_SELECTED_RECIPE: "REMOVE_SELECTED_RECIPE"
}